### ISSUE TITLE
[Feature]: Custom date pre/postfixes as pure markdown meta attributes

### ISSUE THREAD

**Issue by dleeftink** [mgmeyers/obsidian-kanban#393]
### Goal or desired outcome of this feature

Currently, we can custom date formats quite in-depth. However, I would like to be able to switch the @{date} brackets to a pure markdown format.

### Describe the feature

Specifically, I would like to use (\`date\`) to be my default datetime format, but other formatting options would surely suit more use cases than mine.

The added benefit of my proposed format is that tasks can be formatted like so, conflating date and time into a single component:

~~~
- [x] ( 211126 (`15:43:01`)) task a
- [ ] ( 211127 (`15:44:12`)) task b
- [ ] ( 211128 (`15:45:23`)) task c
~~~

Rendering as follows outside kanban boards:
- [x] ( 211126 (`15:43:01`)) task a
- [ ] ( 211127 (`15:44:12`)) task b
- [ ] ( 211128 (`15:45:23`)) task c

Notice also that the inclusion or omission of backticks would inform the parser to include/exclude a timestamp on the card.

Furthermore, when the space between [ ] and () is removed (either by hand or regex), tasks are automatically linked to daily notes, their alternate text displaying the time (ideally, date/time formats remain customisable to taste):

- [x]( 211126 (`15:43:01`)) task a
- [ ]( 211127 (`15:44:12`)) task b
- [ ]( 211128 (`15:45:23`)) task c

In fact, any meta information might be included this way, as markdown links have built in annotation facilities. This would require the kanban parser to parse task like so: 

~~~
     v -- no a space in between
- [x]( link ( attribute )) > task a
- [o]( item ( description )) > task b
- [ ]( hidden ( information )) > task c
~~~

Here, the distinction between `o`, `x` and ` ` marks open, closed and hidden task information:

- [x]( link ( attribute )) > task a
- [o]( item ( description )) > task b
- [ ]( hidden ( information )) > task c

With the above scheme you are then only 'one step' away from greatly increasing a kanban's board functionality, with meta information encoded in pure markdown.

**Comment by coltoneshaw** [comment]
I'd be interested in this as well, but specifically adjusting the `@{}` behavior of a date. It seems to conflict with some other date plugins like Tasks that I have enabled.
