### ISSUE TITLE
[Feature]: Add option to use the date format of the Tasks plugin / ensure compatibility with Tasks plugin

### ISSUE THREAD

**Issue by jonas-sk** [mgmeyers/obsidian-kanban#969]
### Goal or desired outcome of this feature

Right now, tasks created in the Kanban board are not necessarily seen as tasks by the popular [Tasks](https://github.com/obsidian-tasks-group/obsidian-tasks) plugin. By default, they're missing the `#tasks` tag (which is easy to add manually). More importantly, however, the Kanban plugin uses a completely different date format and fails to recognize the date format used by Obsidian Tasks. Hence, cards/tasks in the Kanban board would not show up in a tasks query that requires a certain date and adding a Tasks-compatible card/task to Kanban will break this plugin's date functionality.

Effectively, if you want your cards to show up as tasks in e.g. your queries and have a working date for display in the Kanban board, you need to add the date twice right now. 

### Describe the feature

Add a toggle in the settings to use the `📅 YYYY-MM-DD` format for dates, rather than the `@YYYY-MM-DD` format. In addition, even if `@` is used, tasks that use the Tasks format should still be recognized. 

Furthermore, a solution needs to be found that when `#tasks` is used to trigger the Tasks plugin for a particular card, whether the Tasks date selector or Kanban date selector is used. Even when the Tasks date selector is used, it should automatically trigger the special formatting for dates that Kanban uses.

### Can you think of any alternatives or work-arounds?

Setting 📅 as the trigger symbol does not work. The reason is that Tasks uses the `📅 YYYY-MM-DD` format (note also the space inbetween), while Kanban uses either the `📅[[YYYY-MM-DD]]` or `📅{YYYY-MM-DD}` format, both of which are incompatible. In addition, adding the 📅 via Tasks quick menu doesn't even trigger Kanban's date selector. This can only be done by adding the emoji via an emoji keyboard.

**Comment by mgmeyers** [comment]
<img width="284" alt="Screenshot 2024-05-29 at 8 32 03 AM" src="https://github.com/mgmeyers/obsidian-kanban/assets/2694747/7ee4d7d9-6095-4106-a823-2790b697a77d">


@jonas-sk The latest version of the plugin integrates with the task plugin's auto suggest. So you can acheive compatibility by using that instead of the Kanban plugin's date trigger

**Comment by jamiejenkins** [comment]
This does work to enter the date - but to get the functionality working in the kanban card and as a task in TASKS I have to also enter the date in @{2024-06-01} format.

Example:
`- [ ] TESTING DATE 📅 2024-06-06 @{2024-06-06}`
![image](https://github.com/mgmeyers/obsidian-kanban/assets/1328740/02b70c56-9db5-4117-b01c-c0acb99c4548)

![image](https://github.com/mgmeyers/obsidian-kanban/assets/1328740/04607e26-0fc8-4e15-812f-63c710dca1cd)

**Comment by mgmeyers** [comment]
@jamiejenkins What do you mean by `but to get the functionality working in the kanban card`? What functionality are you referring to?

**Comment by mgmeyers** [comment]
Also, this setting might be relevant: <img width="775" alt="Screenshot 2024-06-06 at 9 26 19 AM" src="https://github.com/mgmeyers/obsidian-kanban/assets/2694747/f1aeb9f0-f9f2-449d-bccd-fc3e6cb480cd">

**Comment by jamiejenkins** [comment]
If I don't also add the date in @{2024-06-06} format the relative date doesn't show up and it doesn't seem to be recognized as a date when looking at the Kanban card.

![image](https://github.com/mgmeyers/obsidian-kanban/assets/1328740/6820bd1e-184f-457b-bbce-63417819c65b)

**Comment by HumanError13** [comment]
I can only amend to this issue. Finding a way to make both date formats compatible would be highly appreciated.

Is there any possibility to make Kanban optionally recognize `📅 YYYY-MM-DD` as date format instead of `📅{YYYY-MM-DD}` ?

**Comment by claremacrae** [comment]
> However, it does not seem to work for the people here as intended, so this issue should be tagged as bug-report instead of feature request.

Hi, Tasks author/maintainer here... Just chopping in to try and help...

No, it's not a bug report, as there are no steps to reproduce the problem.

So it's not actually possible for a contributor to reproduce the problem, and therefore understand if it is even a bug, and if so, whether they have fixed it...

By steps, [I mean this kind of thing](https://publish.obsidian.md/tasks/Support+and+Help/Report+a+Bug#Example+'Steps+to+reproduce'):

![image](https://github.com/user-attachments/assets/5fa48784-e898-4823-abc6-921fe66aa7c9)

**Comment by claremacrae** [comment]
It's up to @mgmeyers to say whether more info is preferred here, or a new bug report created..

**Comment by HumanError13** [comment]
Thanks, @claremacrae. I would happily provide such a bug report, if I find some time. I can provide it here and it can be copied to a new bug report, if preferred.

**Comment by mgmeyers** [comment]
Yes, @HumanError13 I'll need more detail. As far as I can tell this does work as expected: 

https://github.com/user-attachments/assets/40487b4c-d308-4ae7-866f-092d5497afaf

In what way is it not working for you?

**Comment by Cyber-Syntax** [comment]
> Yes, @HumanError13 I'll need more detail. As far as I can tell this does work as expected:
> Screen.Recording.2024-10-08.at.9.21.03.AM.mov
> 
> In what way is it not working for you?

This is work for me but adding via mouse is not work.
I debug some:
```
- [ ] Changed '@' to  '📅' on this one 📅{2024-11-23}
- [ ] tasks plugin 📅 2024-11-23  
- [ ] kanban default settings. Closed send date to card footer. @{2024-11-23}
- [ ] kanban default settings with custom task plugin emoji 📅{📅 2024-11-23}
```
It looks like the Kanban plugin is adding dates in curly brackets. If we convert adding dates to Tasks plugin way would solve this problem, maybe?

**Comment by claremacrae** [comment]
Hi @Cyber-Syntax,

Could you write some instructions for how to reproduce the problem you are trying to report?
Be sure to make them specific - such as pasting in some Markdown to paste in, or attaching a Kanban plugin file - and to include details of your Kanban plugin settings...

**Comment by Cyber-Syntax** [comment]
Hey @claremacrae,  

So I wanted to use the task plugin to see my daily tasks in my daily notes, but I actually figured out how to do it thanks to a video from @mgmeyers - it was super helpful! However, when I tried using the Kanban plugin's date add feature with my mouse, I just couldn't get it to work.
# Reproduce
1. I try to add date some of my tasks via mouse click inside kanban plugin by 'add date' option and select date
	1. This would create date inside markdown like this `@{2024-11-23}`
2. I  try to change date trigger and date format `@`  to `📅` which I wasn't saw there was a curly brackets which is won't work but I tried it either way.

	```json
	{
	  "new-note-template": "10_Dashboard/10.02_Templates/reading-template.md",
	  "new-note-folder": "1.INBOX",
	  "tag-colors": [
	    {
	      "tagKey": "#p1",
	      "color": "rgba(253, 2, 2, 1)",
	      "backgroundColor": "rgba(136, 192, 208, 0.1)"
	    },
	  ],
	  "move-dates": true,
	  "date-picker-week-start": 1,
	  "tag-sort": [
	    {
	      "tag": "#q1"
	    },
	  ],
	  "move-tags": true,
	  "show-checkboxes": true,
	  "link-date-to-daily-note": false,
	  "full-list-lane-width": true,
	  "date-colors": [
	    {
	      "distance": 1,
	      "unit": "days",
	      "direction": "after",
	      "isToday": true,
	      "backgroundColor": "rgba(242, 6, 6, 0)"
	    }
	  ],
	  "move-task-metadata": false,
	  "show-relative-date": true,
	  "date-format": "📅 YYYY-MM-DD",
	  "date-trigger": "📅"
	}
	```
3. Full tasks test Markdown code:
```markdown
---

kanban-plugin: board

---

## Backlog



## Todo


## Doing
- [ ] Changed '@' to  '📅' on this one 📅{2024-11-23}
- [ ] tasks plugin 📅 2024-11-23  
- [ ] kanban default settings. Closed send date to card footer. @{2024-11-23}
- [ ] kanban default settings with custom task plugin emoji 📅{📅 2024-11-23}


## Done

**Complete**




%% kanban:settings
```
{"kanban-plugin":"board","list-collapse":[false,false,false,false]}
```
%%
```

**Comment by claremacrae** [comment]
> Any resolution on this issue @claremacrae?

I maintain the Tasks plugin, not this one. 

It’s for @mgmeyers to say if he is at all clear about what is being requested here.

**Comment by NaturallyAsh** [comment]
> Any resolution on this issue @claremacrae? I think I know what @Cyber-Syntax is getting at, as I am experiencing the same issue. When I click the three dots on a card and then click "Edit card", the Tasks auto-suggests pops up as expected:
> <img alt="Screenshot 2024-12-16 at 5 06 33 PM" width="274" src="https://private-user-images.githubusercontent.com/39710346/396286582-7663b751-da37-4a6d-8861-667a57c99f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTU2OTAsIm5iZiI6MTczNjAxNTM5MCwicGF0aCI6Ii8zOTcxMDM0Ni8zOTYyODY1ODItNzY2M2I3NTEtZGEzNy00YTZkLTg4NjEtNjY3YTU3Yzk5ZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE4Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMmM3Yzc2MzQ5ZjhmOWY5MzZlODJiZDJhMDU2NGEzNGFlZGE1ODU4YTAwZDZlZGE1YzZhMmY3MGUyMWFhYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MnYxfnDw5MjKt-kzwNQdYa3KGroFKsGoLRkmJLWSjrk">
> 
> But when I click the three dots on a card, click "Add date", and select a date on the date selector, the date format added to the card is @{date}, which you can also observe when switching from Kanban to Mardown:
> <img alt="Screenshot 2024-12-16 at 5 06 17 PM" width="266" src="https://private-user-images.githubusercontent.com/39710346/396286625-0f2b8142-fd9a-4d97-80ce-059d96fabc18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTU2OTAsIm5iZiI6MTczNjAxNTM5MCwicGF0aCI6Ii8zOTcxMDM0Ni8zOTYyODY2MjUtMGYyYjgxNDItZmQ5YS00ZDk3LTgwY2UtMDU5ZDk2ZmFiYzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE4Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTUyYzU4YzMxMzIzNjYwY2IzNjU5YzJjOGNmNjdkNWIwYjEyMzU1MTg5MTk4Yjk3NTQ5NGQ5YTZlNWJlNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FslmYKmvDUhWcHMN06DAUeLXGdwC2l8p_TDrkkGj5xE"> <img alt="Screenshot 2024-12-16 at 5 20 35 PM" width="402" src="https://private-user-images.githubusercontent.com/39710346/396286648-8a1491bc-d5bf-46b9-9184-fab9514806ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTU2OTAsIm5iZiI6MTczNjAxNTM5MCwicGF0aCI6Ii8zOTcxMDM0Ni8zOTYyODY2NDgtOGExNDkxYmMtZDViZi00NmI5LTkxODQtZmFiOTUxNDgwNmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE4Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjU1ZjRhNTlhY2RlNTViZTE4Y2QwMzhmMGVkZGQ5OWU2OGQwM2E3NTEwNmE2ODEyYzc5YjFmNzQwMjE3NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fRrbDIbXhPwWoN9GwHw_RfYnm2ve9Fy9UAlwiszX5Rk">
> 
> It would be great if clicking "Add date" could insert a date formatted according to the Tasks plugin.

Good day @mgmeyers I was wondering if this is an issue that can be addressed? Or if I can somehow figure out how to implement it myself, I would do a pull request for review or something like that? (Never done a PR before but I can teach myself).
